### ISSUE TITLE
Dates returned does not look right.

### ISSUE THREAD

**Issue by DrMiaow** [TobiasNickel/tder#1]
**19**18-08-03T00:15:18.000Z

**Comment by TobiasNickel** [comment]
thanks, I will take a look at that. 
the thing is, the date in the certificates only provides the year 00 to 99. 
I wonder if I just prefix with 2000 now, or if I should assume +-50 years from now  if that represents a current certificate. I wonder aniway, is it that certificates get "valid again"?

**Comment by DrMiaow** [comment]
Assume '20' + year. If expire.year < created.year assume '21' + year on expiry. 
We will both be dead at the time if civilisation falls because of this decision.  :)

**Comment by TobiasNickel** [comment]
I moved last weekend, next weekend I will do it.

**Comment by TobiasNickel** [comment]
ok, fixed and published in verion 0.0.8.
Thanks a lot for your patience.
